### ISSUE TITLE
Issues connecting to github with fabric8 forge on OpenShift - #569 On fabric8-devops

### ISSUE THREAD

**Issue by vpiduri** [fabric8io/fabric8-forge#544]
Guys, Thanks for your help. I am able to past the maven proxy issue now. Now I am at a point I can check in the project into gogs.
Now I am facing couple of below issues
1. Failed to pull from the remote git repo with credentials UsernamePasswordCredentialsProvider{user: gogsadmin, password length: 0} due: https://github.com/fabric8io/jenkins-pipeline-library.git: cannot open git-upload-pack. This exception is ignored.
2. Failed to command remote repo http://gogs.cp.cnapps-dev.**.com/gogsadmin/boot12.git due: http://gogs.cp.cnapps-dev.gbt.gbtad.com/gogsadmin/boot12.git: cannot open git-upload-pack
org.eclipse.jgit.api.errors.TransportException: http://gogs.cp.cnapps-dev.**.com/gogsadmin/boot12.git: cannot open git-upload-pack

Do we need to pass the credentials to pull from github? Not necessary right, even I pass the credentials they would be ignored. I was able to get it working on my Vagrant box.

Is this something to do with git http.sslVerify? If that is the case how do I update the settings in the fabric8 forge. Please provide your input.

Appreciate your input on this.

I have already had a discussion on this with #davsclaus, #rawlingsj they helped me to fix maven issue - It looks like  this is more appropriate place for forge so just adding a issues here as well.

Thanks!!

**Comment by yvesmien** [comment]
I have the same problem,The pull request doesn't complete by use password, so the f8 app dashboard always wait for the pull request

```
Performing a pull in git repository /tmp/fabric8-forge/jenkinsWorkflows/.git on remote URL: http://gogs/gogsadmin/jenkins-workflow-library.git
Using UsernamePasswordCredentialsProvider{user: gogsadmin, password length: 0}
```

**Comment by jstrachan** [comment]
@seanzhau your issue looks the the Secret for gogsadmin doesn't have a password defined -  its length 0

**Comment by jstrachan** [comment]
@vpiduri are you behind a http proxy I wonder?  Can you git clone those 2 urls from the command line on your laptop?

**Comment by yvesmien** [comment]
@jstrachan  Default account and password are form the configmap, 

```
# oc get configmap/fabric8-forge -o yaml
apiVersion: v1
data:
  fabric8-default-environments: Testing=${namespace}-testing,Staging=${namespace}-staging,Production=${namespace}-prod
  jenkins-gogs-email: gogsadmin@fabric8.local
  jenkins-gogs-password: RedHat$1
  jenkins-gogs-user: gogsadmin
```

I edit the yaml to used other account and password, and I get the message

```
Performing a pull in git repository /tmp/fabric8-forge/jenkinsWorkflows/.git on remote URL: http://gogs/gogsadmin/jenkins-workflow-library.git
Using UsernamePasswordCredentialsProvider{user: test, password length: 0}
```
